{% set name = "jupyter_innotater" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ideonate/jupyter-innotater/archive/refs/heads/master.zip
  sha256: 967fc8801f1cfb976004840a68bc98c0dd87857a0699c06703f53232db0772f6

build:
  noarch: python
  number: 0
  script: cd jupyter-innotater && {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyter-packaging
    - jupyterlab ~=3.0
    - wheel
    - setuptools >=40.8.0
    - nodejs
  run:
    - python >=3.6
    - ipywidgets >=7.1.0
    - jupyter-packaging
    - traitlets
    - jupyterlab
    - numpy >=1.4.0
    - pypng >=0.0.19

test:
  imports:
    - jupyter_innotater

about:
  home: https://github.com/ideonate/jupyter-innotater
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Annotate data including image bounding boxes inline within your Jupyter notebook in python

extra:
  recipe-maintainers:
    - costrouc
    - rigzba21
